// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: adjustments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountAdjustments = `-- name: CountAdjustments :one
SELECT COUNT(*) FROM adjustments
`

func (q *Queries) CountAdjustments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountAdjustments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountAdjustmentsWithFilter = `-- name: CountAdjustmentsWithFilter :one
SELECT COUNT(*)
FROM adjustments a
WHERE ($1::text IS NULL OR a.reference_number ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR a.status = $2)
  AND ($3::uuid IS NULL OR a.created_by = $3)
  AND ($4::date IS NULL OR a.adjustment_date >= $4)
  AND ($5::date IS NULL OR a.adjustment_date <= $5)
`

type CountAdjustmentsWithFilterParams struct {
	Column1 string      `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 pgtype.UUID `json:"column_3"`
	Column4 pgtype.Date `json:"column_4"`
	Column5 pgtype.Date `json:"column_5"`
}

func (q *Queries) CountAdjustmentsWithFilter(ctx context.Context, arg *CountAdjustmentsWithFilterParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountAdjustmentsWithFilter,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateAdjustment = `-- name: CreateAdjustment :one
INSERT INTO adjustments (reference_number, adjustment_date, warehouse_id, total_quantity, reason, status, created_by, processed_by, processed_date, notes, external_reference)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, reference_number, adjustment_date, total_quantity, reason, status, created_by, processed_by, processed_date, notes, created_at, updated_at, external_reference, warehouse_id
`

type CreateAdjustmentParams struct {
	ReferenceNumber   string             `json:"reference_number"`
	AdjustmentDate    pgtype.Date        `json:"adjustment_date"`
	WarehouseID       pgtype.UUID        `json:"warehouse_id"`
	TotalQuantity     int32              `json:"total_quantity"`
	Reason            *string            `json:"reason"`
	Status            string             `json:"status"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	ProcessedBy       pgtype.UUID        `json:"processed_by"`
	ProcessedDate     pgtype.Timestamptz `json:"processed_date"`
	Notes             *string            `json:"notes"`
	ExternalReference *string            `json:"external_reference"`
}

func (q *Queries) CreateAdjustment(ctx context.Context, arg *CreateAdjustmentParams) (*Adjustment, error) {
	row := q.db.QueryRow(ctx, CreateAdjustment,
		arg.ReferenceNumber,
		arg.AdjustmentDate,
		arg.WarehouseID,
		arg.TotalQuantity,
		arg.Reason,
		arg.Status,
		arg.CreatedBy,
		arg.ProcessedBy,
		arg.ProcessedDate,
		arg.Notes,
		arg.ExternalReference,
	)
	var i Adjustment
	err := row.Scan(
		&i.ID,
		&i.ReferenceNumber,
		&i.AdjustmentDate,
		&i.TotalQuantity,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.ProcessedBy,
		&i.ProcessedDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalReference,
		&i.WarehouseID,
	)
	return &i, err
}

const CreateAdjustmentItem = `-- name: CreateAdjustmentItem :one
INSERT INTO adjustment_items (adjustment_id, product_id, quantity, reason, cost_price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, adjustment_id, product_id, quantity, reason, created_at, cost_price
`

type CreateAdjustmentItemParams struct {
	AdjustmentID pgtype.UUID    `json:"adjustment_id"`
	ProductID    pgtype.UUID    `json:"product_id"`
	Quantity     int32          `json:"quantity"`
	Reason       *string        `json:"reason"`
	CostPrice    pgtype.Numeric `json:"cost_price"`
}

func (q *Queries) CreateAdjustmentItem(ctx context.Context, arg *CreateAdjustmentItemParams) (*AdjustmentItem, error) {
	row := q.db.QueryRow(ctx, CreateAdjustmentItem,
		arg.AdjustmentID,
		arg.ProductID,
		arg.Quantity,
		arg.Reason,
		arg.CostPrice,
	)
	var i AdjustmentItem
	err := row.Scan(
		&i.ID,
		&i.AdjustmentID,
		&i.ProductID,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
		&i.CostPrice,
	)
	return &i, err
}

const DeleteAdjustment = `-- name: DeleteAdjustment :exec
DELETE FROM adjustments WHERE id = $1
`

func (q *Queries) DeleteAdjustment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteAdjustment, id)
	return err
}

const DeleteAdjustmentItem = `-- name: DeleteAdjustmentItem :exec
DELETE FROM adjustment_items WHERE id = $1
`

func (q *Queries) DeleteAdjustmentItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteAdjustmentItem, id)
	return err
}

const DeleteAdjustmentItemsByAdjustmentId = `-- name: DeleteAdjustmentItemsByAdjustmentId :exec
DELETE FROM adjustment_items WHERE adjustment_id = $1
`

func (q *Queries) DeleteAdjustmentItemsByAdjustmentId(ctx context.Context, adjustmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteAdjustmentItemsByAdjustmentId, adjustmentID)
	return err
}

const GetAdjustment = `-- name: GetAdjustment :one
SELECT a.id, a.reference_number, a.adjustment_date, a.total_quantity, a.reason, a.status, a.created_by, a.processed_by, a.processed_date, a.notes, a.created_at, a.updated_at, a.external_reference, a.warehouse_id, 
       u.first_name as created_by_first_name, u.last_name as created_by_last_name,
       p.first_name as processed_by_first_name, p.last_name as processed_by_last_name,
       w.name as warehouse_name
FROM adjustments a
LEFT JOIN users u ON a.created_by = u.id
LEFT JOIN users p ON a.processed_by = p.id
LEFT JOIN warehouses w ON a.warehouse_id = w.id
WHERE a.id = $1
`

type GetAdjustmentRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ReferenceNumber      string             `json:"reference_number"`
	AdjustmentDate       pgtype.Date        `json:"adjustment_date"`
	TotalQuantity        int32              `json:"total_quantity"`
	Reason               *string            `json:"reason"`
	Status               string             `json:"status"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	ProcessedBy          pgtype.UUID        `json:"processed_by"`
	ProcessedDate        pgtype.Timestamptz `json:"processed_date"`
	Notes                *string            `json:"notes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ExternalReference    *string            `json:"external_reference"`
	WarehouseID          pgtype.UUID        `json:"warehouse_id"`
	CreatedByFirstName   *string            `json:"created_by_first_name"`
	CreatedByLastName    *string            `json:"created_by_last_name"`
	ProcessedByFirstName *string            `json:"processed_by_first_name"`
	ProcessedByLastName  *string            `json:"processed_by_last_name"`
	WarehouseName        *string            `json:"warehouse_name"`
}

func (q *Queries) GetAdjustment(ctx context.Context, id pgtype.UUID) (*GetAdjustmentRow, error) {
	row := q.db.QueryRow(ctx, GetAdjustment, id)
	var i GetAdjustmentRow
	err := row.Scan(
		&i.ID,
		&i.ReferenceNumber,
		&i.AdjustmentDate,
		&i.TotalQuantity,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.ProcessedBy,
		&i.ProcessedDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalReference,
		&i.WarehouseID,
		&i.CreatedByFirstName,
		&i.CreatedByLastName,
		&i.ProcessedByFirstName,
		&i.ProcessedByLastName,
		&i.WarehouseName,
	)
	return &i, err
}

const GetAdjustmentByReferenceNumber = `-- name: GetAdjustmentByReferenceNumber :one
SELECT a.id, a.reference_number, a.adjustment_date, a.total_quantity, a.reason, a.status, a.created_by, a.processed_by, a.processed_date, a.notes, a.created_at, a.updated_at, a.external_reference, a.warehouse_id, 
       u.first_name as created_by_first_name, u.last_name as created_by_last_name,
       p.first_name as processed_by_first_name, p.last_name as processed_by_last_name,
       w.name as warehouse_name
FROM adjustments a
LEFT JOIN users u ON a.created_by = u.id
LEFT JOIN users p ON a.processed_by = p.id
LEFT JOIN warehouses w ON a.warehouse_id = w.id
WHERE a.reference_number = $1
`

type GetAdjustmentByReferenceNumberRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ReferenceNumber      string             `json:"reference_number"`
	AdjustmentDate       pgtype.Date        `json:"adjustment_date"`
	TotalQuantity        int32              `json:"total_quantity"`
	Reason               *string            `json:"reason"`
	Status               string             `json:"status"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	ProcessedBy          pgtype.UUID        `json:"processed_by"`
	ProcessedDate        pgtype.Timestamptz `json:"processed_date"`
	Notes                *string            `json:"notes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ExternalReference    *string            `json:"external_reference"`
	WarehouseID          pgtype.UUID        `json:"warehouse_id"`
	CreatedByFirstName   *string            `json:"created_by_first_name"`
	CreatedByLastName    *string            `json:"created_by_last_name"`
	ProcessedByFirstName *string            `json:"processed_by_first_name"`
	ProcessedByLastName  *string            `json:"processed_by_last_name"`
	WarehouseName        *string            `json:"warehouse_name"`
}

func (q *Queries) GetAdjustmentByReferenceNumber(ctx context.Context, referenceNumber string) (*GetAdjustmentByReferenceNumberRow, error) {
	row := q.db.QueryRow(ctx, GetAdjustmentByReferenceNumber, referenceNumber)
	var i GetAdjustmentByReferenceNumberRow
	err := row.Scan(
		&i.ID,
		&i.ReferenceNumber,
		&i.AdjustmentDate,
		&i.TotalQuantity,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.ProcessedBy,
		&i.ProcessedDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalReference,
		&i.WarehouseID,
		&i.CreatedByFirstName,
		&i.CreatedByLastName,
		&i.ProcessedByFirstName,
		&i.ProcessedByLastName,
		&i.WarehouseName,
	)
	return &i, err
}

const GetAdjustmentItems = `-- name: GetAdjustmentItems :many
SELECT ai.id, ai.adjustment_id, ai.product_id, ai.quantity, ai.reason, ai.created_at, ai.cost_price, 
       p.name as product_name, p.sku as product_sku
FROM adjustment_items ai
JOIN products p ON ai.product_id = p.id
WHERE ai.adjustment_id = $1
ORDER BY ai.created_at
`

type GetAdjustmentItemsRow struct {
	ID           pgtype.UUID        `json:"id"`
	AdjustmentID pgtype.UUID        `json:"adjustment_id"`
	ProductID    pgtype.UUID        `json:"product_id"`
	Quantity     int32              `json:"quantity"`
	Reason       *string            `json:"reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	ProductName  string             `json:"product_name"`
	ProductSku   string             `json:"product_sku"`
}

func (q *Queries) GetAdjustmentItems(ctx context.Context, adjustmentID pgtype.UUID) ([]*GetAdjustmentItemsRow, error) {
	rows, err := q.db.Query(ctx, GetAdjustmentItems, adjustmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAdjustmentItemsRow{}
	for rows.Next() {
		var i GetAdjustmentItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdjustmentID,
			&i.ProductID,
			&i.Quantity,
			&i.Reason,
			&i.CreatedAt,
			&i.CostPrice,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAdjustments = `-- name: ListAdjustments :many
SELECT a.id, a.reference_number, a.adjustment_date, a.total_quantity, a.reason, a.status, a.created_by, a.processed_by, a.processed_date, a.notes, a.created_at, a.updated_at, a.external_reference, a.warehouse_id, 
       u.first_name as created_by_first_name, u.last_name as created_by_last_name,
       p.first_name as processed_by_first_name, p.last_name as processed_by_last_name,
       w.name as warehouse_name
FROM adjustments a
LEFT JOIN users u ON a.created_by = u.id
LEFT JOIN users p ON a.processed_by = p.id
LEFT JOIN warehouses w ON a.warehouse_id = w.id
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdjustmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdjustmentsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ReferenceNumber      string             `json:"reference_number"`
	AdjustmentDate       pgtype.Date        `json:"adjustment_date"`
	TotalQuantity        int32              `json:"total_quantity"`
	Reason               *string            `json:"reason"`
	Status               string             `json:"status"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	ProcessedBy          pgtype.UUID        `json:"processed_by"`
	ProcessedDate        pgtype.Timestamptz `json:"processed_date"`
	Notes                *string            `json:"notes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ExternalReference    *string            `json:"external_reference"`
	WarehouseID          pgtype.UUID        `json:"warehouse_id"`
	CreatedByFirstName   *string            `json:"created_by_first_name"`
	CreatedByLastName    *string            `json:"created_by_last_name"`
	ProcessedByFirstName *string            `json:"processed_by_first_name"`
	ProcessedByLastName  *string            `json:"processed_by_last_name"`
	WarehouseName        *string            `json:"warehouse_name"`
}

func (q *Queries) ListAdjustments(ctx context.Context, arg *ListAdjustmentsParams) ([]*ListAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, ListAdjustments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAdjustmentsRow{}
	for rows.Next() {
		var i ListAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceNumber,
			&i.AdjustmentDate,
			&i.TotalQuantity,
			&i.Reason,
			&i.Status,
			&i.CreatedBy,
			&i.ProcessedBy,
			&i.ProcessedDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalReference,
			&i.WarehouseID,
			&i.CreatedByFirstName,
			&i.CreatedByLastName,
			&i.ProcessedByFirstName,
			&i.ProcessedByLastName,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAdjustmentsWithFilter = `-- name: ListAdjustmentsWithFilter :many
SELECT a.id, a.reference_number, a.adjustment_date, a.total_quantity, a.reason, a.status, a.created_by, a.processed_by, a.processed_date, a.notes, a.created_at, a.updated_at, a.external_reference, a.warehouse_id, 
       u.first_name as created_by_first_name, u.last_name as created_by_last_name,
       p.first_name as processed_by_first_name, p.last_name as processed_by_last_name,
       w.name as warehouse_name
FROM adjustments a
LEFT JOIN users u ON a.created_by = u.id
LEFT JOIN users p ON a.processed_by = p.id
LEFT JOIN warehouses w ON a.warehouse_id = w.id
WHERE ($1::text IS NULL OR a.reference_number ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR a.status = $2)
  AND ($3::uuid IS NULL OR a.created_by = $3)
  AND ($4::date IS NULL OR a.adjustment_date >= $4)
  AND ($5::date IS NULL OR a.adjustment_date <= $5)
ORDER BY a.created_at DESC
LIMIT $6 OFFSET $7
`

type ListAdjustmentsWithFilterParams struct {
	Column1 string      `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 pgtype.UUID `json:"column_3"`
	Column4 pgtype.Date `json:"column_4"`
	Column5 pgtype.Date `json:"column_5"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListAdjustmentsWithFilterRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ReferenceNumber      string             `json:"reference_number"`
	AdjustmentDate       pgtype.Date        `json:"adjustment_date"`
	TotalQuantity        int32              `json:"total_quantity"`
	Reason               *string            `json:"reason"`
	Status               string             `json:"status"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	ProcessedBy          pgtype.UUID        `json:"processed_by"`
	ProcessedDate        pgtype.Timestamptz `json:"processed_date"`
	Notes                *string            `json:"notes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ExternalReference    *string            `json:"external_reference"`
	WarehouseID          pgtype.UUID        `json:"warehouse_id"`
	CreatedByFirstName   *string            `json:"created_by_first_name"`
	CreatedByLastName    *string            `json:"created_by_last_name"`
	ProcessedByFirstName *string            `json:"processed_by_first_name"`
	ProcessedByLastName  *string            `json:"processed_by_last_name"`
	WarehouseName        *string            `json:"warehouse_name"`
}

func (q *Queries) ListAdjustmentsWithFilter(ctx context.Context, arg *ListAdjustmentsWithFilterParams) ([]*ListAdjustmentsWithFilterRow, error) {
	rows, err := q.db.Query(ctx, ListAdjustmentsWithFilter,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAdjustmentsWithFilterRow{}
	for rows.Next() {
		var i ListAdjustmentsWithFilterRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceNumber,
			&i.AdjustmentDate,
			&i.TotalQuantity,
			&i.Reason,
			&i.Status,
			&i.CreatedBy,
			&i.ProcessedBy,
			&i.ProcessedDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalReference,
			&i.WarehouseID,
			&i.CreatedByFirstName,
			&i.CreatedByLastName,
			&i.ProcessedByFirstName,
			&i.ProcessedByLastName,
			&i.WarehouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateAdjustment = `-- name: UpdateAdjustment :one
UPDATE adjustments 
SET reference_number = $2, adjustment_date = $3, warehouse_id = $4, total_quantity = $5, reason = $6, 
    status = $7, processed_by = $8, processed_date = $9, notes = $10, updated_at = NOW()
WHERE id = $1
RETURNING id, reference_number, adjustment_date, total_quantity, reason, status, created_by, processed_by, processed_date, notes, created_at, updated_at, external_reference, warehouse_id
`

type UpdateAdjustmentParams struct {
	ID              pgtype.UUID        `json:"id"`
	ReferenceNumber string             `json:"reference_number"`
	AdjustmentDate  pgtype.Date        `json:"adjustment_date"`
	WarehouseID     pgtype.UUID        `json:"warehouse_id"`
	TotalQuantity   int32              `json:"total_quantity"`
	Reason          *string            `json:"reason"`
	Status          string             `json:"status"`
	ProcessedBy     pgtype.UUID        `json:"processed_by"`
	ProcessedDate   pgtype.Timestamptz `json:"processed_date"`
	Notes           *string            `json:"notes"`
}

func (q *Queries) UpdateAdjustment(ctx context.Context, arg *UpdateAdjustmentParams) (*Adjustment, error) {
	row := q.db.QueryRow(ctx, UpdateAdjustment,
		arg.ID,
		arg.ReferenceNumber,
		arg.AdjustmentDate,
		arg.WarehouseID,
		arg.TotalQuantity,
		arg.Reason,
		arg.Status,
		arg.ProcessedBy,
		arg.ProcessedDate,
		arg.Notes,
	)
	var i Adjustment
	err := row.Scan(
		&i.ID,
		&i.ReferenceNumber,
		&i.AdjustmentDate,
		&i.TotalQuantity,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.ProcessedBy,
		&i.ProcessedDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalReference,
		&i.WarehouseID,
	)
	return &i, err
}

const UpdateAdjustmentItem = `-- name: UpdateAdjustmentItem :one
UPDATE adjustment_items 
SET product_id = $2, quantity = $3, reason = $4, cost_price = $5
WHERE id = $1
RETURNING id, adjustment_id, product_id, quantity, reason, created_at, cost_price
`

type UpdateAdjustmentItemParams struct {
	ID        pgtype.UUID    `json:"id"`
	ProductID pgtype.UUID    `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	Reason    *string        `json:"reason"`
	CostPrice pgtype.Numeric `json:"cost_price"`
}

func (q *Queries) UpdateAdjustmentItem(ctx context.Context, arg *UpdateAdjustmentItemParams) (*AdjustmentItem, error) {
	row := q.db.QueryRow(ctx, UpdateAdjustmentItem,
		arg.ID,
		arg.ProductID,
		arg.Quantity,
		arg.Reason,
		arg.CostPrice,
	)
	var i AdjustmentItem
	err := row.Scan(
		&i.ID,
		&i.AdjustmentID,
		&i.ProductID,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
		&i.CostPrice,
	)
	return &i, err
}
