// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    reference_type,
    reference_id,
    file_name,
    file_path,
    file_size,
    file_type
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, file_name, file_path, file_size, file_type, uploaded_at, created_at, updated_at, reference_type, reference_id
`

type CreateDocumentParams struct {
	ReferenceType string      `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
	FileName      string      `json:"file_name"`
	FilePath      string      `json:"file_path"`
	FileSize      int64       `json:"file_size"`
	FileType      string      `json:"file_type"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg *CreateDocumentParams) (*Document, error) {
	row := q.db.QueryRow(ctx, CreateDocument,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.FileType,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileType,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferenceType,
		&i.ReferenceID,
	)
	return &i, err
}

const DeleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteDocument, id)
	return err
}

const GetDocumentByID = `-- name: GetDocumentByID :one
SELECT id, file_name, file_path, file_size, file_type, uploaded_at, created_at, updated_at, reference_type, reference_id FROM documents WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (*Document, error) {
	row := q.db.QueryRow(ctx, GetDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileType,
		&i.UploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferenceType,
		&i.ReferenceID,
	)
	return &i, err
}

const GetDocumentsByPurchaseOrder = `-- name: GetDocumentsByPurchaseOrder :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_at, created_at, updated_at, reference_type, reference_id FROM documents 
WHERE reference_type = 'purchase_order' AND reference_id = $1 
ORDER BY uploaded_at DESC
`

func (q *Queries) GetDocumentsByPurchaseOrder(ctx context.Context, referenceID pgtype.UUID) ([]*Document, error) {
	rows, err := q.db.Query(ctx, GetDocumentsByPurchaseOrder, referenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReferenceType,
			&i.ReferenceID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetDocumentsByReference = `-- name: GetDocumentsByReference :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_at, created_at, updated_at, reference_type, reference_id FROM documents 
WHERE reference_type = $1 AND reference_id = $2 
ORDER BY uploaded_at DESC
`

type GetDocumentsByReferenceParams struct {
	ReferenceType string      `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
}

func (q *Queries) GetDocumentsByReference(ctx context.Context, arg *GetDocumentsByReferenceParams) ([]*Document, error) {
	rows, err := q.db.Query(ctx, GetDocumentsByReference, arg.ReferenceType, arg.ReferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReferenceType,
			&i.ReferenceID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetDocumentsByTypeOnly = `-- name: GetDocumentsByTypeOnly :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_at, created_at, updated_at, reference_type, reference_id FROM documents 
WHERE reference_type = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) GetDocumentsByTypeOnly(ctx context.Context, referenceType string) ([]*Document, error) {
	rows, err := q.db.Query(ctx, GetDocumentsByTypeOnly, referenceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReferenceType,
			&i.ReferenceID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAllDocuments = `-- name: ListAllDocuments :many
SELECT id, file_name, file_path, file_size, file_type, uploaded_at, created_at, updated_at, reference_type, reference_id FROM documents 
ORDER BY uploaded_at DESC
LIMIT $1 OFFSET $2
`

type ListAllDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllDocuments(ctx context.Context, arg *ListAllDocumentsParams) ([]*Document, error) {
	rows, err := q.db.Query(ctx, ListAllDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileType,
			&i.UploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReferenceType,
			&i.ReferenceID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
