// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsActive    *bool              `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	Sku         string             `json:"sku"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Category    *string            `json:"category"`
	UnitPrice   pgtype.Numeric     `json:"unit_price"`
	IsActive    *bool              `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	SupplierID  pgtype.UUID        `json:"supplier_id"`
}

type PurchaseOrder struct {
	ID                   pgtype.UUID        `json:"id"`
	PoNumber             string             `json:"po_number"`
	SupplierName         string             `json:"supplier_name"`
	SupplierContact      *string            `json:"supplier_contact"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	Status               string             `json:"status"`
	OrderDate            pgtype.Date        `json:"order_date"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	ReceivedDate         pgtype.Date        `json:"received_date"`
	Notes                *string            `json:"notes"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PurchaseOrderItem struct {
	ID               pgtype.UUID        `json:"id"`
	PurchaseOrderID  pgtype.UUID        `json:"purchase_order_id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Quantity         int32              `json:"quantity"`
	UnitPrice        pgtype.Numeric     `json:"unit_price"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	ReceivedQuantity *int32             `json:"received_quantity"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SalesOrder struct {
	ID                   pgtype.UUID        `json:"id"`
	SoNumber             string             `json:"so_number"`
	CustomerName         string             `json:"customer_name"`
	CustomerContact      *string            `json:"customer_contact"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	Status               string             `json:"status"`
	OrderDate            pgtype.Date        `json:"order_date"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	ShippedDate          pgtype.Date        `json:"shipped_date"`
	DeliveredDate        pgtype.Date        `json:"delivered_date"`
	Notes                *string            `json:"notes"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type SalesOrderItem struct {
	ID              pgtype.UUID        `json:"id"`
	SalesOrderID    pgtype.UUID        `json:"sales_order_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	WarehouseID     pgtype.UUID        `json:"warehouse_id"`
	Quantity        int32              `json:"quantity"`
	UnitPrice       pgtype.Numeric     `json:"unit_price"`
	TotalPrice      pgtype.Numeric     `json:"total_price"`
	ShippedQuantity *int32             `json:"shipped_quantity"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type StockLevel struct {
	ID                pgtype.UUID        `json:"id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	WarehouseID       pgtype.UUID        `json:"warehouse_id"`
	Quantity          int32              `json:"quantity"`
	ReservedQuantity  int32              `json:"reserved_quantity"`
	AvailableQuantity *int32             `json:"available_quantity"`
	MinStockLevel     *int32             `json:"min_stock_level"`
	MaxStockLevel     *int32             `json:"max_stock_level"`
	LastUpdated       pgtype.Timestamptz `json:"last_updated"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type StockMovement struct {
	ID            pgtype.UUID        `json:"id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	WarehouseID   pgtype.UUID        `json:"warehouse_id"`
	MovementType  string             `json:"movement_type"`
	Quantity      int32              `json:"quantity"`
	ReferenceType *string            `json:"reference_type"`
	ReferenceID   pgtype.UUID        `json:"reference_id"`
	Reason        *string            `json:"reason"`
	UserID        pgtype.UUID        `json:"user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProcessedBy   pgtype.UUID        `json:"processed_by"`
	ProcessedDate pgtype.Timestamptz `json:"processed_date"`
	CostPrice     pgtype.Numeric     `json:"cost_price"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
}

type Supplier struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	ContactPerson *string            `json:"contact_person"`
	Email         *string            `json:"email"`
	Phone         *string            `json:"phone"`
	Address       *string            `json:"address"`
	City          *string            `json:"city"`
	State         *string            `json:"state"`
	Country       *string            `json:"country"`
	PostalCode    *string            `json:"postal_code"`
	IsActive      *bool              `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Role         string             `json:"role"`
	IsActive     *bool              `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Warehouse struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Location      string             `json:"location"`
	Address       *string            `json:"address"`
	ContactPerson *string            `json:"contact_person"`
	ContactPhone  *string            `json:"contact_phone"`
	IsActive      *bool              `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
