// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Main adjustments table for inventory adjustments
type Adjustment struct {
	ID pgtype.UUID `json:"id"`
	// Unique reference number for the adjustment (e.g., ADJ-2024-001)
	ReferenceNumber string      `json:"reference_number"`
	AdjustmentDate  pgtype.Date `json:"adjustment_date"`
	// Total quantity of all items in the adjustment
	TotalQuantity int32   `json:"total_quantity"`
	Reason        *string `json:"reason"`
	// Current status of the adjustment
	Status string `json:"status"`
	// User who created the adjustment
	CreatedBy pgtype.UUID `json:"created_by"`
	// User who processed/approved the adjustment
	ProcessedBy   pgtype.UUID        `json:"processed_by"`
	ProcessedDate pgtype.Timestamptz `json:"processed_date"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Individual items within an adjustment
type AdjustmentItem struct {
	ID           pgtype.UUID `json:"id"`
	AdjustmentID pgtype.UUID `json:"adjustment_id"`
	ProductID    pgtype.UUID `json:"product_id"`
	WarehouseID  pgtype.UUID `json:"warehouse_id"`
	// Quantity adjustment (positive for add, negative for subtract)
	Quantity int32 `json:"quantity"`
	// Reason for this specific item adjustment
	Reason    *string            `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsActive    *bool              `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Document struct {
	ID               pgtype.UUID        `json:"id"`
	PurchaseOrderID  pgtype.UUID        `json:"purchase_order_id"`
	FileName         string             `json:"file_name"`
	FilePath         string             `json:"file_path"`
	FileSize         int64              `json:"file_size"`
	FileType         string             `json:"file_type"`
	UploadedAt       pgtype.Timestamptz `json:"uploaded_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	HasPoReference   *bool              `json:"has_po_reference"`
	HasMatchingDate  *bool              `json:"has_matching_date"`
	ValidationStatus *string            `json:"validation_status"`
	ValidationNotes  *string            `json:"validation_notes"`
}

type Product struct {
	ID            pgtype.UUID        `json:"id"`
	Sku           string             `json:"sku"`
	Name          string             `json:"name"`
	Description   *string            `json:"description"`
	Category      *string            `json:"category"`
	UnitPrice     pgtype.Numeric     `json:"unit_price"`
	IsActive      *bool              `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	SupplierID    pgtype.UUID        `json:"supplier_id"`
	MinStockLevel int32              `json:"min_stock_level"`
}

type PurchaseOrder struct {
	ID                   pgtype.UUID        `json:"id"`
	PoNumber             string             `json:"po_number"`
	SupplierName         string             `json:"supplier_name"`
	SupplierContact      *string            `json:"supplier_contact"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	Status               string             `json:"status"`
	OrderDate            pgtype.Date        `json:"order_date"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	ReceivedDate         pgtype.Date        `json:"received_date"`
	Notes                *string            `json:"notes"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PurchaseOrderItem struct {
	ID               pgtype.UUID        `json:"id"`
	PurchaseOrderID  pgtype.UUID        `json:"purchase_order_id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Quantity         int32              `json:"quantity"`
	UnitPrice        pgtype.Numeric     `json:"unit_price"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	ReceivedQuantity *int32             `json:"received_quantity"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SalesOrder struct {
	ID                   pgtype.UUID        `json:"id"`
	SoNumber             string             `json:"so_number"`
	CustomerName         string             `json:"customer_name"`
	CustomerContact      *string            `json:"customer_contact"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	Status               string             `json:"status"`
	OrderDate            pgtype.Date        `json:"order_date"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	ShippedDate          pgtype.Date        `json:"shipped_date"`
	DeliveredDate        pgtype.Date        `json:"delivered_date"`
	Notes                *string            `json:"notes"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type SalesOrderItem struct {
	ID              pgtype.UUID        `json:"id"`
	SalesOrderID    pgtype.UUID        `json:"sales_order_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	WarehouseID     pgtype.UUID        `json:"warehouse_id"`
	Quantity        int32              `json:"quantity"`
	UnitPrice       pgtype.Numeric     `json:"unit_price"`
	TotalPrice      pgtype.Numeric     `json:"total_price"`
	ShippedQuantity *int32             `json:"shipped_quantity"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type StockLevel struct {
	ID                pgtype.UUID        `json:"id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	WarehouseID       pgtype.UUID        `json:"warehouse_id"`
	Quantity          int32              `json:"quantity"`
	ReservedQuantity  int32              `json:"reserved_quantity"`
	AvailableQuantity *int32             `json:"available_quantity"`
	MinStockLevel     *int32             `json:"min_stock_level"`
	MaxStockLevel     *int32             `json:"max_stock_level"`
	LastUpdated       pgtype.Timestamptz `json:"last_updated"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type StockMovement struct {
	ID              pgtype.UUID        `json:"id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	WarehouseID     pgtype.UUID        `json:"warehouse_id"`
	MovementType    string             `json:"movement_type"`
	Quantity        int32              `json:"quantity"`
	ReferenceType   *string            `json:"reference_type"`
	ReferenceID     pgtype.UUID        `json:"reference_id"`
	Reason          *string            `json:"reason"`
	UserID          pgtype.UUID        `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProcessedBy     pgtype.UUID        `json:"processed_by"`
	ProcessedDate   pgtype.Timestamptz `json:"processed_date"`
	CostPrice       pgtype.Numeric     `json:"cost_price"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	ReferenceNumber *string            `json:"reference_number"`
}

type Supplier struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	ContactPerson *string            `json:"contact_person"`
	Email         *string            `json:"email"`
	Phone         *string            `json:"phone"`
	Address       *string            `json:"address"`
	City          *string            `json:"city"`
	State         *string            `json:"state"`
	Country       *string            `json:"country"`
	PostalCode    *string            `json:"postal_code"`
	IsActive      *bool              `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Main transfers table for inventory transfers between warehouses
type Transfer struct {
	ID pgtype.UUID `json:"id"`
	// Unique reference number for the transfer (e.g., TRF-2024-001)
	ReferenceNumber string      `json:"reference_number"`
	TransferDate    pgtype.Date `json:"transfer_date"`
	FromWarehouseID pgtype.UUID `json:"from_warehouse_id"`
	ToWarehouseID   pgtype.UUID `json:"to_warehouse_id"`
	// Total quantity of all items in the transfer
	TotalQuantity int32 `json:"total_quantity"`
	// Current status of the transfer
	Status string  `json:"status"`
	Reason *string `json:"reason"`
	// User who created the transfer
	CreatedBy pgtype.UUID `json:"created_by"`
	// User who processed the transfer
	ProcessedBy   pgtype.UUID        `json:"processed_by"`
	ProcessedDate pgtype.Timestamptz `json:"processed_date"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Individual items within a transfer
type TransferItem struct {
	ID         pgtype.UUID `json:"id"`
	TransferID pgtype.UUID `json:"transfer_id"`
	ProductID  pgtype.UUID `json:"product_id"`
	// Quantity to transfer (always positive)
	Quantity int32 `json:"quantity"`
	// Reason for this specific item transfer
	Reason    *string            `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Role         string             `json:"role"`
	IsActive     *bool              `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Warehouse struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Location      string             `json:"location"`
	Address       *string            `json:"address"`
	ContactPerson *string            `json:"contact_person"`
	ContactPhone  *string            `json:"contact_phone"`
	IsActive      *bool              `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
