// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelPurchaseOrder(ctx context.Context, id pgtype.UUID) (*PurchaseOrder, error)
	CountAdjustments(ctx context.Context) (int64, error)
	CountAdjustmentsWithFilter(ctx context.Context, arg *CountAdjustmentsWithFilterParams) (int64, error)
	CountCategoriesWithFilter(ctx context.Context, arg *CountCategoriesWithFilterParams) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountProductsWithFilter(ctx context.Context, arg *CountProductsWithFilterParams) (int64, error)
	CountPurchaseOrders(ctx context.Context) (int64, error)
	CountPurchaseOrdersWithFilter(ctx context.Context, arg *CountPurchaseOrdersWithFilterParams) (int64, error)
	CountSalesOrders(ctx context.Context) (int64, error)
	CountSalesOrdersWithFilter(ctx context.Context, arg *CountSalesOrdersWithFilterParams) (int64, error)
	CountStockLevels(ctx context.Context) (int64, error)
	CountStockLevelsWithFilter(ctx context.Context, arg *CountStockLevelsWithFilterParams) (int64, error)
	CountStockMovements(ctx context.Context) (int64, error)
	CountStockMovementsWithFilter(ctx context.Context, arg *CountStockMovementsWithFilterParams) (int64, error)
	CountSuppliersWithFilter(ctx context.Context, arg *CountSuppliersWithFilterParams) (int64, error)
	CountTransfers(ctx context.Context) (int64, error)
	CountTransfersWithFilter(ctx context.Context, arg *CountTransfersWithFilterParams) (int64, error)
	CountWarehouses(ctx context.Context, arg *CountWarehousesParams) (int64, error)
	CreateAdjustment(ctx context.Context, arg *CreateAdjustmentParams) (*Adjustment, error)
	CreateAdjustmentItem(ctx context.Context, arg *CreateAdjustmentItemParams) (*AdjustmentItem, error)
	CreateCategory(ctx context.Context, arg *CreateCategoryParams) (*Category, error)
	CreateDocument(ctx context.Context, arg *CreateDocumentParams) (*Document, error)
	CreateProduct(ctx context.Context, arg *CreateProductParams) (*Product, error)
	CreatePurchaseOrder(ctx context.Context, arg *CreatePurchaseOrderParams) (*PurchaseOrder, error)
	CreateSalesOrder(ctx context.Context, arg *CreateSalesOrderParams) (*SalesOrder, error)
	CreateStockLevel(ctx context.Context, arg *CreateStockLevelParams) (*StockLevel, error)
	CreateStockMovement(ctx context.Context, arg *CreateStockMovementParams) (*StockMovement, error)
	CreateSupplier(ctx context.Context, arg *CreateSupplierParams) (*Supplier, error)
	CreateTransfer(ctx context.Context, arg *CreateTransferParams) (*Transfer, error)
	CreateTransferItem(ctx context.Context, arg *CreateTransferItemParams) (*TransferItem, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	CreateWarehouse(ctx context.Context, arg *CreateWarehouseParams) (*Warehouse, error)
	DeleteAdjustment(ctx context.Context, id pgtype.UUID) error
	DeleteAdjustmentItem(ctx context.Context, id pgtype.UUID) error
	DeleteAdjustmentItemsByAdjustmentId(ctx context.Context, adjustmentID pgtype.UUID) error
	DeleteCategory(ctx context.Context, id pgtype.UUID) error
	DeleteDocument(ctx context.Context, id pgtype.UUID) error
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteSupplier(ctx context.Context, id pgtype.UUID) error
	DeleteTransfer(ctx context.Context, id pgtype.UUID) error
	DeleteTransferItem(ctx context.Context, id pgtype.UUID) error
	DeleteTransferItemsByTransferId(ctx context.Context, transferID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DeleteWarehouse(ctx context.Context, id pgtype.UUID) error
	GetAdjustment(ctx context.Context, id pgtype.UUID) (*GetAdjustmentRow, error)
	GetAdjustmentByReferenceNumber(ctx context.Context, referenceNumber string) (*GetAdjustmentByReferenceNumberRow, error)
	GetAdjustmentItems(ctx context.Context, adjustmentID pgtype.UUID) ([]*GetAdjustmentItemsRow, error)
	GetCategory(ctx context.Context, id pgtype.UUID) (*Category, error)
	GetCategoryByName(ctx context.Context, name string) (*Category, error)
	GetDocumentByID(ctx context.Context, id pgtype.UUID) (*Document, error)
	GetDocumentsByPurchaseOrder(ctx context.Context, purchaseOrderID pgtype.UUID) ([]*Document, error)
	GetDocumentsByReference(ctx context.Context, arg *GetDocumentsByReferenceParams) ([]*Document, error)
	GetLowStockItems(ctx context.Context) ([]*GetLowStockItemsRow, error)
	GetProduct(ctx context.Context, id pgtype.UUID) (*Product, error)
	GetProductBySKU(ctx context.Context, sku string) (*Product, error)
	GetProductsBySupplier(ctx context.Context, supplierID pgtype.UUID) ([]*GetProductsBySupplierRow, error)
	GetPurchaseOrder(ctx context.Context, id pgtype.UUID) (*GetPurchaseOrderRow, error)
	GetPurchaseOrderItems(ctx context.Context, purchaseOrderID pgtype.UUID) ([]*GetPurchaseOrderItemsRow, error)
	GetPurchaseOrderStockMovements(ctx context.Context, referenceID pgtype.UUID) ([]*GetPurchaseOrderStockMovementsRow, error)
	GetSalesOrder(ctx context.Context, id pgtype.UUID) (*GetSalesOrderRow, error)
	GetStockInTransactionDetails(ctx context.Context, referenceID pgtype.UUID) ([]*GetStockInTransactionDetailsRow, error)
	GetStockLevel(ctx context.Context, arg *GetStockLevelParams) (*GetStockLevelRow, error)
	GetSupplier(ctx context.Context, id pgtype.UUID) (*Supplier, error)
	GetSupplierByName(ctx context.Context, name string) (*Supplier, error)
	GetTransfer(ctx context.Context, id pgtype.UUID) (*GetTransferRow, error)
	GetTransferByReferenceNumber(ctx context.Context, referenceNumber string) (*GetTransferByReferenceNumberRow, error)
	GetTransferItems(ctx context.Context, transferID pgtype.UUID) ([]*GetTransferItemsRow, error)
	GetUser(ctx context.Context, id pgtype.UUID) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetWarehouse(ctx context.Context, id pgtype.UUID) (*Warehouse, error)
	ListAdjustments(ctx context.Context, arg *ListAdjustmentsParams) ([]*ListAdjustmentsRow, error)
	ListAdjustmentsWithFilter(ctx context.Context, arg *ListAdjustmentsWithFilterParams) ([]*ListAdjustmentsWithFilterRow, error)
	ListCategories(ctx context.Context) ([]*Category, error)
	ListCategoriesWithFilter(ctx context.Context, arg *ListCategoriesWithFilterParams) ([]*Category, error)
	ListProducts(ctx context.Context, arg *ListProductsParams) ([]*ListProductsRow, error)
	ListProductsWithFilter(ctx context.Context, arg *ListProductsWithFilterParams) ([]*ListProductsWithFilterRow, error)
	ListProductsWithStock(ctx context.Context, arg *ListProductsWithStockParams) ([]*ListProductsWithStockRow, error)
	ListPurchaseOrders(ctx context.Context, arg *ListPurchaseOrdersParams) ([]*ListPurchaseOrdersRow, error)
	ListPurchaseOrdersWithFilter(ctx context.Context, arg *ListPurchaseOrdersWithFilterParams) ([]*ListPurchaseOrdersWithFilterRow, error)
	ListSalesOrders(ctx context.Context, arg *ListSalesOrdersParams) ([]*ListSalesOrdersRow, error)
	ListSalesOrdersWithFilter(ctx context.Context, arg *ListSalesOrdersWithFilterParams) ([]*ListSalesOrdersWithFilterRow, error)
	ListStockInTransactions(ctx context.Context, arg *ListStockInTransactionsParams) ([]*ListStockInTransactionsRow, error)
	ListStockLevels(ctx context.Context, arg *ListStockLevelsParams) ([]*ListStockLevelsRow, error)
	ListStockLevelsWithFilter(ctx context.Context, arg *ListStockLevelsWithFilterParams) ([]*ListStockLevelsWithFilterRow, error)
	ListStockMovements(ctx context.Context, arg *ListStockMovementsParams) ([]*ListStockMovementsRow, error)
	ListStockMovementsWithFilter(ctx context.Context, arg *ListStockMovementsWithFilterParams) ([]*ListStockMovementsWithFilterRow, error)
	ListSuppliers(ctx context.Context) ([]*Supplier, error)
	ListSuppliersWithFilter(ctx context.Context, arg *ListSuppliersWithFilterParams) ([]*Supplier, error)
	ListTransfers(ctx context.Context, arg *ListTransfersParams) ([]*ListTransfersRow, error)
	ListTransfersWithFilter(ctx context.Context, arg *ListTransfersWithFilterParams) ([]*ListTransfersWithFilterRow, error)
	ListUsers(ctx context.Context) ([]*User, error)
	ListWarehouses(ctx context.Context, arg *ListWarehousesParams) ([]*Warehouse, error)
	UpdateAdjustment(ctx context.Context, arg *UpdateAdjustmentParams) (*Adjustment, error)
	UpdateAdjustmentItem(ctx context.Context, arg *UpdateAdjustmentItemParams) (*AdjustmentItem, error)
	UpdateCategory(ctx context.Context, arg *UpdateCategoryParams) (*Category, error)
	UpdateDocumentValidation(ctx context.Context, arg *UpdateDocumentValidationParams) (*Document, error)
	UpdateProduct(ctx context.Context, arg *UpdateProductParams) (*Product, error)
	UpdatePurchaseOrder(ctx context.Context, arg *UpdatePurchaseOrderParams) (*PurchaseOrder, error)
	UpdatePurchaseOrderTotal(ctx context.Context, arg *UpdatePurchaseOrderTotalParams) (*PurchaseOrder, error)
	UpdateReservedQuantity(ctx context.Context, arg *UpdateReservedQuantityParams) (*StockLevel, error)
	UpdateSalesOrder(ctx context.Context, arg *UpdateSalesOrderParams) (*SalesOrder, error)
	UpdateSalesOrderTotal(ctx context.Context, arg *UpdateSalesOrderTotalParams) (*SalesOrder, error)
	UpdateStockLevel(ctx context.Context, arg *UpdateStockLevelParams) (*StockLevel, error)
	UpdateStockQuantity(ctx context.Context, arg *UpdateStockQuantityParams) (*StockLevel, error)
	UpdateSupplier(ctx context.Context, arg *UpdateSupplierParams) (*Supplier, error)
	UpdateTransfer(ctx context.Context, arg *UpdateTransferParams) (*Transfer, error)
	UpdateTransferItem(ctx context.Context, arg *UpdateTransferItemParams) (*TransferItem, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error)
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) (*User, error)
	UpdateWarehouse(ctx context.Context, arg *UpdateWarehouseParams) (*Warehouse, error)
}

var _ Querier = (*Queries)(nil)
