// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCategoriesWithFilter(ctx context.Context, arg *CountCategoriesWithFilterParams) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountProductsWithFilter(ctx context.Context, arg *CountProductsWithFilterParams) (int64, error)
	CountPurchaseOrders(ctx context.Context) (int64, error)
	CountPurchaseOrdersWithFilter(ctx context.Context, arg *CountPurchaseOrdersWithFilterParams) (int64, error)
	CountSalesOrders(ctx context.Context) (int64, error)
	CountSalesOrdersWithFilter(ctx context.Context, arg *CountSalesOrdersWithFilterParams) (int64, error)
	CountStockLevels(ctx context.Context) (int64, error)
	CountStockLevelsWithFilter(ctx context.Context, arg *CountStockLevelsWithFilterParams) (int64, error)
	CountStockMovements(ctx context.Context) (int64, error)
	CountStockMovementsWithFilter(ctx context.Context, arg *CountStockMovementsWithFilterParams) (int64, error)
	CountSuppliersWithFilter(ctx context.Context, arg *CountSuppliersWithFilterParams) (int64, error)
	CountWarehouses(ctx context.Context, arg *CountWarehousesParams) (int64, error)
	CreateCategory(ctx context.Context, arg *CreateCategoryParams) (*Category, error)
	CreateProduct(ctx context.Context, arg *CreateProductParams) (*Product, error)
	CreatePurchaseOrder(ctx context.Context, arg *CreatePurchaseOrderParams) (*PurchaseOrder, error)
	CreateSalesOrder(ctx context.Context, arg *CreateSalesOrderParams) (*SalesOrder, error)
	CreateStockLevel(ctx context.Context, arg *CreateStockLevelParams) (*StockLevel, error)
	CreateStockMovement(ctx context.Context, arg *CreateStockMovementParams) (*StockMovement, error)
	CreateSupplier(ctx context.Context, arg *CreateSupplierParams) (*Supplier, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	CreateWarehouse(ctx context.Context, arg *CreateWarehouseParams) (*Warehouse, error)
	DeleteCategory(ctx context.Context, id pgtype.UUID) error
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteSupplier(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DeleteWarehouse(ctx context.Context, id pgtype.UUID) error
	GetCategory(ctx context.Context, id pgtype.UUID) (*Category, error)
	GetCategoryByName(ctx context.Context, name string) (*Category, error)
	GetLowStockItems(ctx context.Context) ([]*GetLowStockItemsRow, error)
	GetProduct(ctx context.Context, id pgtype.UUID) (*Product, error)
	GetProductBySKU(ctx context.Context, sku string) (*Product, error)
	GetProductsBySupplier(ctx context.Context, supplierID pgtype.UUID) ([]*GetProductsBySupplierRow, error)
	GetPurchaseOrder(ctx context.Context, id pgtype.UUID) (*GetPurchaseOrderRow, error)
	GetSalesOrder(ctx context.Context, id pgtype.UUID) (*GetSalesOrderRow, error)
	GetStockInTransactionDetails(ctx context.Context, referenceID pgtype.UUID) ([]*GetStockInTransactionDetailsRow, error)
	GetStockLevel(ctx context.Context, arg *GetStockLevelParams) (*GetStockLevelRow, error)
	GetSupplier(ctx context.Context, id pgtype.UUID) (*Supplier, error)
	GetSupplierByName(ctx context.Context, name string) (*Supplier, error)
	GetUser(ctx context.Context, id pgtype.UUID) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetWarehouse(ctx context.Context, id pgtype.UUID) (*Warehouse, error)
	ListCategories(ctx context.Context) ([]*Category, error)
	ListCategoriesWithFilter(ctx context.Context, arg *ListCategoriesWithFilterParams) ([]*Category, error)
	ListProducts(ctx context.Context, arg *ListProductsParams) ([]*ListProductsRow, error)
	ListProductsWithFilter(ctx context.Context, arg *ListProductsWithFilterParams) ([]*ListProductsWithFilterRow, error)
	ListProductsWithStock(ctx context.Context, arg *ListProductsWithStockParams) ([]*ListProductsWithStockRow, error)
	ListPurchaseOrders(ctx context.Context, arg *ListPurchaseOrdersParams) ([]*ListPurchaseOrdersRow, error)
	ListPurchaseOrdersWithFilter(ctx context.Context, arg *ListPurchaseOrdersWithFilterParams) ([]*ListPurchaseOrdersWithFilterRow, error)
	ListSalesOrders(ctx context.Context, arg *ListSalesOrdersParams) ([]*ListSalesOrdersRow, error)
	ListSalesOrdersWithFilter(ctx context.Context, arg *ListSalesOrdersWithFilterParams) ([]*ListSalesOrdersWithFilterRow, error)
	ListStockInTransactions(ctx context.Context, arg *ListStockInTransactionsParams) ([]*ListStockInTransactionsRow, error)
	ListStockLevels(ctx context.Context, arg *ListStockLevelsParams) ([]*ListStockLevelsRow, error)
	ListStockLevelsWithFilter(ctx context.Context, arg *ListStockLevelsWithFilterParams) ([]*ListStockLevelsWithFilterRow, error)
	ListStockMovements(ctx context.Context, arg *ListStockMovementsParams) ([]*ListStockMovementsRow, error)
	ListStockMovementsWithFilter(ctx context.Context, arg *ListStockMovementsWithFilterParams) ([]*ListStockMovementsWithFilterRow, error)
	ListSuppliers(ctx context.Context) ([]*Supplier, error)
	ListSuppliersWithFilter(ctx context.Context, arg *ListSuppliersWithFilterParams) ([]*Supplier, error)
	ListUsers(ctx context.Context) ([]*User, error)
	ListWarehouses(ctx context.Context, arg *ListWarehousesParams) ([]*Warehouse, error)
	UpdateCategory(ctx context.Context, arg *UpdateCategoryParams) (*Category, error)
	UpdateProduct(ctx context.Context, arg *UpdateProductParams) (*Product, error)
	UpdatePurchaseOrder(ctx context.Context, arg *UpdatePurchaseOrderParams) (*PurchaseOrder, error)
	UpdatePurchaseOrderTotal(ctx context.Context, arg *UpdatePurchaseOrderTotalParams) (*PurchaseOrder, error)
	UpdateReservedQuantity(ctx context.Context, arg *UpdateReservedQuantityParams) (*StockLevel, error)
	UpdateSalesOrder(ctx context.Context, arg *UpdateSalesOrderParams) (*SalesOrder, error)
	UpdateSalesOrderTotal(ctx context.Context, arg *UpdateSalesOrderTotalParams) (*SalesOrder, error)
	UpdateStockLevel(ctx context.Context, arg *UpdateStockLevelParams) (*StockLevel, error)
	UpdateStockQuantity(ctx context.Context, arg *UpdateStockQuantityParams) (*StockLevel, error)
	UpdateSupplier(ctx context.Context, arg *UpdateSupplierParams) (*Supplier, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error)
	UpdateUserPassword(ctx context.Context, arg *UpdateUserPasswordParams) (*User, error)
	UpdateWarehouse(ctx context.Context, arg *UpdateWarehouseParams) (*Warehouse, error)
}

var _ Querier = (*Queries)(nil)
