// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
    reference_number,
    from_warehouse_id,
    to_warehouse_id,
    reason,
    notes,
    transfer_date,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, reference_number, transfer_date, from_warehouse_id, to_warehouse_id, total_quantity, status, reason, created_by, processed_by, processed_date, notes, created_at, updated_at
`

type CreateTransferParams struct {
	ReferenceNumber string      `json:"reference_number"`
	FromWarehouseID pgtype.UUID `json:"from_warehouse_id"`
	ToWarehouseID   pgtype.UUID `json:"to_warehouse_id"`
	Reason          *string     `json:"reason"`
	Notes           *string     `json:"notes"`
	TransferDate    pgtype.Date `json:"transfer_date"`
	CreatedBy       pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg *CreateTransferParams) (*Transfer, error) {
	row := q.db.QueryRow(ctx, CreateTransfer,
		arg.ReferenceNumber,
		arg.FromWarehouseID,
		arg.ToWarehouseID,
		arg.Reason,
		arg.Notes,
		arg.TransferDate,
		arg.CreatedBy,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ReferenceNumber,
		&i.TransferDate,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TotalQuantity,
		&i.Status,
		&i.Reason,
		&i.CreatedBy,
		&i.ProcessedBy,
		&i.ProcessedDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const CreateTransferItem = `-- name: CreateTransferItem :one
INSERT INTO transfer_items (
    transfer_id,
    product_id,
    quantity
) VALUES (
    $1, $2, $3
) RETURNING id, transfer_id, product_id, quantity, reason, created_at
`

type CreateTransferItemParams struct {
	TransferID pgtype.UUID `json:"transfer_id"`
	ProductID  pgtype.UUID `json:"product_id"`
	Quantity   int32       `json:"quantity"`
}

func (q *Queries) CreateTransferItem(ctx context.Context, arg *CreateTransferItemParams) (*TransferItem, error) {
	row := q.db.QueryRow(ctx, CreateTransferItem, arg.TransferID, arg.ProductID, arg.Quantity)
	var i TransferItem
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ProductID,
		&i.Quantity,
		&i.Reason,
		&i.CreatedAt,
	)
	return &i, err
}

const DeleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfers WHERE id = $1
`

func (q *Queries) DeleteTransfer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteTransfer, id)
	return err
}

const GetTransfer = `-- name: GetTransfer :one
SELECT 
    t.id, t.reference_number, t.transfer_date, t.from_warehouse_id, t.to_warehouse_id, t.total_quantity, t.status, t.reason, t.created_by, t.processed_by, t.processed_date, t.notes, t.created_at, t.updated_at,
    wf.name as from_warehouse_name,
    wf.location as from_warehouse_location,
    wt.name as to_warehouse_name,
    wt.location as to_warehouse_location,
    u.first_name || ' ' || u.last_name as created_by_name
FROM transfers t
JOIN warehouses wf ON t.from_warehouse_id = wf.id
JOIN warehouses wt ON t.to_warehouse_id = wt.id
JOIN users u ON t.created_by = u.id
WHERE t.id = $1
`

type GetTransferRow struct {
	ID                    pgtype.UUID        `json:"id"`
	ReferenceNumber       string             `json:"reference_number"`
	TransferDate          pgtype.Date        `json:"transfer_date"`
	FromWarehouseID       pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID         pgtype.UUID        `json:"to_warehouse_id"`
	TotalQuantity         int32              `json:"total_quantity"`
	Status                string             `json:"status"`
	Reason                *string            `json:"reason"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	ProcessedBy           pgtype.UUID        `json:"processed_by"`
	ProcessedDate         pgtype.Timestamptz `json:"processed_date"`
	Notes                 *string            `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FromWarehouseName     string             `json:"from_warehouse_name"`
	FromWarehouseLocation string             `json:"from_warehouse_location"`
	ToWarehouseName       string             `json:"to_warehouse_name"`
	ToWarehouseLocation   string             `json:"to_warehouse_location"`
	CreatedByName         interface{}        `json:"created_by_name"`
}

func (q *Queries) GetTransfer(ctx context.Context, id pgtype.UUID) (*GetTransferRow, error) {
	row := q.db.QueryRow(ctx, GetTransfer, id)
	var i GetTransferRow
	err := row.Scan(
		&i.ID,
		&i.ReferenceNumber,
		&i.TransferDate,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TotalQuantity,
		&i.Status,
		&i.Reason,
		&i.CreatedBy,
		&i.ProcessedBy,
		&i.ProcessedDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FromWarehouseName,
		&i.FromWarehouseLocation,
		&i.ToWarehouseName,
		&i.ToWarehouseLocation,
		&i.CreatedByName,
	)
	return &i, err
}

const GetTransferByReferenceNumber = `-- name: GetTransferByReferenceNumber :one
SELECT 
    t.id, t.reference_number, t.transfer_date, t.from_warehouse_id, t.to_warehouse_id, t.total_quantity, t.status, t.reason, t.created_by, t.processed_by, t.processed_date, t.notes, t.created_at, t.updated_at,
    wf.name as from_warehouse_name,
    wf.location as from_warehouse_location,
    wt.name as to_warehouse_name,
    wt.location as to_warehouse_location,
    u.first_name || ' ' || u.last_name as created_by_name
FROM transfers t
JOIN warehouses wf ON t.from_warehouse_id = wf.id
JOIN warehouses wt ON t.to_warehouse_id = wt.id
JOIN users u ON t.created_by = u.id
WHERE t.reference_number = $1
`

type GetTransferByReferenceNumberRow struct {
	ID                    pgtype.UUID        `json:"id"`
	ReferenceNumber       string             `json:"reference_number"`
	TransferDate          pgtype.Date        `json:"transfer_date"`
	FromWarehouseID       pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID         pgtype.UUID        `json:"to_warehouse_id"`
	TotalQuantity         int32              `json:"total_quantity"`
	Status                string             `json:"status"`
	Reason                *string            `json:"reason"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	ProcessedBy           pgtype.UUID        `json:"processed_by"`
	ProcessedDate         pgtype.Timestamptz `json:"processed_date"`
	Notes                 *string            `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FromWarehouseName     string             `json:"from_warehouse_name"`
	FromWarehouseLocation string             `json:"from_warehouse_location"`
	ToWarehouseName       string             `json:"to_warehouse_name"`
	ToWarehouseLocation   string             `json:"to_warehouse_location"`
	CreatedByName         interface{}        `json:"created_by_name"`
}

func (q *Queries) GetTransferByReferenceNumber(ctx context.Context, referenceNumber string) (*GetTransferByReferenceNumberRow, error) {
	row := q.db.QueryRow(ctx, GetTransferByReferenceNumber, referenceNumber)
	var i GetTransferByReferenceNumberRow
	err := row.Scan(
		&i.ID,
		&i.ReferenceNumber,
		&i.TransferDate,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TotalQuantity,
		&i.Status,
		&i.Reason,
		&i.CreatedBy,
		&i.ProcessedBy,
		&i.ProcessedDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FromWarehouseName,
		&i.FromWarehouseLocation,
		&i.ToWarehouseName,
		&i.ToWarehouseLocation,
		&i.CreatedByName,
	)
	return &i, err
}

const GetTransferItems = `-- name: GetTransferItems :many
SELECT 
    ti.id, ti.transfer_id, ti.product_id, ti.quantity, ti.reason, ti.created_at,
    p.name as product_name,
    p.sku as product_sku
FROM transfer_items ti
JOIN products p ON ti.product_id = p.id
WHERE ti.transfer_id = $1
ORDER BY p.name
`

type GetTransferItemsRow struct {
	ID          pgtype.UUID        `json:"id"`
	TransferID  pgtype.UUID        `json:"transfer_id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	Quantity    int32              `json:"quantity"`
	Reason      *string            `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProductName string             `json:"product_name"`
	ProductSku  string             `json:"product_sku"`
}

func (q *Queries) GetTransferItems(ctx context.Context, transferID pgtype.UUID) ([]*GetTransferItemsRow, error) {
	rows, err := q.db.Query(ctx, GetTransferItems, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetTransferItemsRow{}
	for rows.Next() {
		var i GetTransferItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.ProductID,
			&i.Quantity,
			&i.Reason,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTransferWithItems = `-- name: GetTransferWithItems :many
SELECT 
    t.id as transfer_id,
    t.reference_number,
    t.from_warehouse_id,
    t.to_warehouse_id,
    t.reason,
    t.notes,
    t.transfer_date,
    t.total_quantity,
    t.status,
    t.created_at,
    wf.name as from_warehouse_name,
    wf.location as from_warehouse_location,
    wt.name as to_warehouse_name,
    wt.location as to_warehouse_location,
    u.first_name || ' ' || u.last_name as created_by_name,
    ti.id as item_id,
    ti.product_id,
    ti.quantity as item_quantity,
    p.name as product_name,
    p.sku as product_sku
FROM transfers t
JOIN warehouses wf ON t.from_warehouse_id = wf.id
JOIN warehouses wt ON t.to_warehouse_id = wt.id
JOIN users u ON t.created_by = u.id
LEFT JOIN transfer_items ti ON t.id = ti.transfer_id
LEFT JOIN products p ON ti.product_id = p.id
ORDER BY t.created_at DESC, p.name
`

type GetTransferWithItemsRow struct {
	TransferID            pgtype.UUID        `json:"transfer_id"`
	ReferenceNumber       string             `json:"reference_number"`
	FromWarehouseID       pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID         pgtype.UUID        `json:"to_warehouse_id"`
	Reason                *string            `json:"reason"`
	Notes                 *string            `json:"notes"`
	TransferDate          pgtype.Date        `json:"transfer_date"`
	TotalQuantity         int32              `json:"total_quantity"`
	Status                string             `json:"status"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	FromWarehouseName     string             `json:"from_warehouse_name"`
	FromWarehouseLocation string             `json:"from_warehouse_location"`
	ToWarehouseName       string             `json:"to_warehouse_name"`
	ToWarehouseLocation   string             `json:"to_warehouse_location"`
	CreatedByName         interface{}        `json:"created_by_name"`
	ItemID                pgtype.UUID        `json:"item_id"`
	ProductID             pgtype.UUID        `json:"product_id"`
	ItemQuantity          *int32             `json:"item_quantity"`
	ProductName           *string            `json:"product_name"`
	ProductSku            *string            `json:"product_sku"`
}

func (q *Queries) GetTransferWithItems(ctx context.Context) ([]*GetTransferWithItemsRow, error) {
	rows, err := q.db.Query(ctx, GetTransferWithItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetTransferWithItemsRow{}
	for rows.Next() {
		var i GetTransferWithItemsRow
		if err := rows.Scan(
			&i.TransferID,
			&i.ReferenceNumber,
			&i.FromWarehouseID,
			&i.ToWarehouseID,
			&i.Reason,
			&i.Notes,
			&i.TransferDate,
			&i.TotalQuantity,
			&i.Status,
			&i.CreatedAt,
			&i.FromWarehouseName,
			&i.FromWarehouseLocation,
			&i.ToWarehouseName,
			&i.ToWarehouseLocation,
			&i.CreatedByName,
			&i.ItemID,
			&i.ProductID,
			&i.ItemQuantity,
			&i.ProductName,
			&i.ProductSku,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTransfers = `-- name: GetTransfers :many
SELECT 
    t.id, t.reference_number, t.transfer_date, t.from_warehouse_id, t.to_warehouse_id, t.total_quantity, t.status, t.reason, t.created_by, t.processed_by, t.processed_date, t.notes, t.created_at, t.updated_at,
    wf.name as from_warehouse_name,
    wf.location as from_warehouse_location,
    wt.name as to_warehouse_name,
    wt.location as to_warehouse_location,
    u.first_name || ' ' || u.last_name as created_by_name
FROM transfers t
JOIN warehouses wf ON t.from_warehouse_id = wf.id
JOIN warehouses wt ON t.to_warehouse_id = wt.id
JOIN users u ON t.created_by = u.id
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type GetTransfersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetTransfersRow struct {
	ID                    pgtype.UUID        `json:"id"`
	ReferenceNumber       string             `json:"reference_number"`
	TransferDate          pgtype.Date        `json:"transfer_date"`
	FromWarehouseID       pgtype.UUID        `json:"from_warehouse_id"`
	ToWarehouseID         pgtype.UUID        `json:"to_warehouse_id"`
	TotalQuantity         int32              `json:"total_quantity"`
	Status                string             `json:"status"`
	Reason                *string            `json:"reason"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	ProcessedBy           pgtype.UUID        `json:"processed_by"`
	ProcessedDate         pgtype.Timestamptz `json:"processed_date"`
	Notes                 *string            `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FromWarehouseName     string             `json:"from_warehouse_name"`
	FromWarehouseLocation string             `json:"from_warehouse_location"`
	ToWarehouseName       string             `json:"to_warehouse_name"`
	ToWarehouseLocation   string             `json:"to_warehouse_location"`
	CreatedByName         interface{}        `json:"created_by_name"`
}

func (q *Queries) GetTransfers(ctx context.Context, arg *GetTransfersParams) ([]*GetTransfersRow, error) {
	rows, err := q.db.Query(ctx, GetTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetTransfersRow{}
	for rows.Next() {
		var i GetTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceNumber,
			&i.TransferDate,
			&i.FromWarehouseID,
			&i.ToWarehouseID,
			&i.TotalQuantity,
			&i.Status,
			&i.Reason,
			&i.CreatedBy,
			&i.ProcessedBy,
			&i.ProcessedDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromWarehouseName,
			&i.FromWarehouseLocation,
			&i.ToWarehouseName,
			&i.ToWarehouseLocation,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateTransferStatus = `-- name: UpdateTransferStatus :one
UPDATE transfers 
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, reference_number, transfer_date, from_warehouse_id, to_warehouse_id, total_quantity, status, reason, created_by, processed_by, processed_date, notes, created_at, updated_at
`

type UpdateTransferStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg *UpdateTransferStatusParams) (*Transfer, error) {
	row := q.db.QueryRow(ctx, UpdateTransferStatus, arg.ID, arg.Status)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ReferenceNumber,
		&i.TransferDate,
		&i.FromWarehouseID,
		&i.ToWarehouseID,
		&i.TotalQuantity,
		&i.Status,
		&i.Reason,
		&i.CreatedBy,
		&i.ProcessedBy,
		&i.ProcessedDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
