// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warehouses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountWarehouses = `-- name: CountWarehouses :one
SELECT COUNT(*) FROM warehouses
WHERE 
    ($1 = '' OR name ILIKE '%' || $1 || '%')
    AND is_active = $2
`

type CountWarehousesParams struct {
	Column1  interface{} `json:"column_1"`
	IsActive *bool       `json:"is_active"`
}

func (q *Queries) CountWarehouses(ctx context.Context, arg *CountWarehousesParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountWarehouses, arg.Column1, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (
    name,
    location,
    address,
    contact_person,
    contact_phone,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, location, address, contact_person, contact_phone, is_active, created_at, updated_at
`

type CreateWarehouseParams struct {
	Name          string  `json:"name"`
	Location      string  `json:"location"`
	Address       *string `json:"address"`
	ContactPerson *string `json:"contact_person"`
	ContactPhone  *string `json:"contact_phone"`
	IsActive      *bool   `json:"is_active"`
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg *CreateWarehouseParams) (*Warehouse, error) {
	row := q.db.QueryRow(ctx, CreateWarehouse,
		arg.Name,
		arg.Location,
		arg.Address,
		arg.ContactPerson,
		arg.ContactPhone,
		arg.IsActive,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Address,
		&i.ContactPerson,
		&i.ContactPhone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeleteWarehouse = `-- name: DeleteWarehouse :exec
DELETE FROM warehouses
WHERE id = $1
`

func (q *Queries) DeleteWarehouse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteWarehouse, id)
	return err
}

const GetWarehouse = `-- name: GetWarehouse :one
SELECT id, name, location, address, contact_person, contact_phone, is_active, created_at, updated_at FROM warehouses
WHERE id = $1
`

func (q *Queries) GetWarehouse(ctx context.Context, id pgtype.UUID) (*Warehouse, error) {
	row := q.db.QueryRow(ctx, GetWarehouse, id)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Address,
		&i.ContactPerson,
		&i.ContactPhone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const ListWarehouses = `-- name: ListWarehouses :many
SELECT id, name, location, address, contact_person, contact_phone, is_active, created_at, updated_at FROM warehouses
WHERE 
    ($1 = '' OR name ILIKE '%' || $1 || '%')
    AND is_active = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListWarehousesParams struct {
	Column1  interface{} `json:"column_1"`
	IsActive *bool       `json:"is_active"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListWarehouses(ctx context.Context, arg *ListWarehousesParams) ([]*Warehouse, error) {
	rows, err := q.db.Query(ctx, ListWarehouses,
		arg.Column1,
		arg.IsActive,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Warehouse{}
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.Address,
			&i.ContactPerson,
			&i.ContactPhone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateWarehouse = `-- name: UpdateWarehouse :one
UPDATE warehouses
SET 
    name = $2,
    location = $3,
    address = $4,
    contact_person = $5,
    contact_phone = $6,
    is_active = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, location, address, contact_person, contact_phone, is_active, created_at, updated_at
`

type UpdateWarehouseParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Location      string      `json:"location"`
	Address       *string     `json:"address"`
	ContactPerson *string     `json:"contact_person"`
	ContactPhone  *string     `json:"contact_phone"`
	IsActive      *bool       `json:"is_active"`
}

func (q *Queries) UpdateWarehouse(ctx context.Context, arg *UpdateWarehouseParams) (*Warehouse, error) {
	row := q.db.QueryRow(ctx, UpdateWarehouse,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.Address,
		arg.ContactPerson,
		arg.ContactPhone,
		arg.IsActive,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Address,
		&i.ContactPerson,
		&i.ContactPhone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
